### ISSUE TITLE
Is there a place where we can just say "please no"?

### ISSUE THREAD

**Issue by taoeffect** [tc39/proposal-pipeline-operator#285]
JavaScript's syntax is already sufficiently complicated enough.

Have you people seen what happened to C -> C++? Is that your goal too?

**Comment by ctcpip** [comment]
https://matrix.to/#/%23tc39-general:matrix.org

**Comment by ljharb** [comment]
@taoeffect please be reminded that TC39 has a [Code of Conduct](https://tc39.es/code-of-conduct/), and everyone is expected to follow it.

**Comment by hr8** [comment]
> @taoeffect please be reminded that TC39 has a [Code of Conduct](https://tc39.es/code-of-conduct/), and everyone is expected to follow it.

@ljharb nothing in his title or comment is a violation of any Code of Conduct, unless the Code is "you must like the pipeline, you are not allowed to dislike it". I would suggest people be careful to reach for CoC arguments, as in recent times, I have found people are just using it to shut down discussion (as is also evidenced by the issue closure), rather than allowing for nuanced and respectful disagreement.

People are allowed to say "I dont like this". And you should welcome that, and part of any healthy adult should be the attribute of seeing other viewpoints, and possibly even admitting when something you made is bad and/or a failure.

**Comment by ljharb** [comment]
@hr8 as a member of the CoC committee, I don't agree, which is why I commented. It's not about dislike - dislike is fine - it's about an unproductive tone. Things like "you people" and an absence of good faith arguments is not appropriate.

The user already apologized for their behavior in Matrix, and agreed with my assessment, so your perspective is simply wrong, objectively. Sealioning in to a discussion you're not a part of isn't productive, either. I'm going to hide both of these comments as off topic.

**Comment by ctcpip** [comment]
@hr8 everyone is happy to discuss the proposal in good faith.  however, this issue clearly contained nothing substantive that we can actually reason about.  closing the issue was the correct course of action.

not only was discussion not shut down, we pointed to a place to discuss -- in other words, answered the question: "Is there a place where we can just say "please no"?  and discussion did take place there.

as far as the CoC is concerned, it's clear to see how this issue several of the main tenets of the CoC:

- Be respectful
- Be friendly and patient
- Be inclusive
- Be considerate
- Be careful in the words that you choose
- When we disagree, try to understand why

**Comment by hr8** [comment]
https://github.com/tc39/proposal-pipeline-operator/issues/286

**Comment by hr8** [comment]
OK, then, lets see if its actually possible for someone to post a respectful issue on this matter, without it being shut down. I have made a second attempt (with this issue #285 being the first). thanks for the feedback

**Comment by hr8** [comment]
OK, I see from the immediate closure of the new issue, that its in fact not possible to even have a constructive discussion on the matter.

**Comment by ljharb** [comment]
@hr8 no, it's not, because as a stage 2 proposal, this question has been resolved: yes, it should exist. There are many older issues you're welcome to read if you're curious about what's been discussed, but further discussion about "no" is not appropriate here anymore.
